# Configuration for golangci-lint

run:
  timeout: 1m

output:
  sort-results: true

linters:
  disable-all: true

  enable:
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
