language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux
  - windows
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
    - os: windows

env:
  - EK_TEST_PORT=8080

before_install:
  - if [[ "$TRAVIS_OS_NAME" =~ (osx|linux) ]] ; then make deps ; fi
  - if [[ "$TRAVIS_OS_NAME" =~ (osx|linux) ]] ; then make deps-test ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" =~ (osx|linux) ]] ; then .travis/script.sh 10 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then .travis/windows.sh 10 ; fi
