name: GoDoc

on:
  create

jobs:
  GoSumDB:
    name: Trigger GoSum DB
    runs-on: ubuntu-latest

    env:
      GO_SUM: https://sum.golang.org/lookup

    steps:
      - name: Send request to GoSum DB
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]] ; then
            full_ver=$(echo ${GITHUB_REF} | cut -f3 -d'/')
            major_ver=$(echo ${full_ver} | cut -f1 -d'.')
            curl -s ${{env.GO_SUM}}/pkg.re/${{github.repository}}.${major_ver}@${full_ver}
          fi
