name: Go

on: [push, pull_request]

jobs:
  Ubuntu:
    name: Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.8.x', '1.9.x', '1.10.x', '1.11.x', '1.12.x']

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Checkout
        uses: actions/checkout@master

      - name: Download dependencies
        run: make deps

      - name: Download test dependencies
        run: make deps-test

      - name: Run tests
        run: .travis/script.sh 10
        env: 
          EK_TEST_PORT: 8080

  macOS:
    name: Mac OS X
    runs-on: macOS-latest

    strategy:
      matrix:
        go: [ '1.8.x', '1.9.x', '1.10.x', '1.11.x', '1.12.x']

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Checkout
        uses: actions/checkout@master

      - name: Download dependencies
        run: make deps

      - name: Download test dependencies
        run: make deps-test

      - name: Run tests
        run: .travis/script.sh 10
        env: 
          EK_TEST_PORT: 8080

  Windows:
    name: Windows
    runs-on: windows-latest

    strategy:
      matrix:
        go: [ '1.8.x', '1.9.x', '1.10.x', '1.11.x', '1.12.x']

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Checkout
        uses: actions/checkout@master

      - name: Run tests
        run: .travis/windows.sh 10
